name: docker-envsubst

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-envsubst.yml'
      - 'docker-envsubst/**'

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: docker-envsubst
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: keeword/docker-envsubst
          tag_with_ref: true
