name: py2exe

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/py2exe.yml'
      - '!py2exe/**'

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          path: py2exe
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: keeword/py2exe
          tag_with_ref: true
