name: qbittorrent

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/qbittorrent.yml'
      - 'qbittorrent/**'

jobs:
  build:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: qbittorrent
          push: true
          tags: keeword/qbittorrent:latest
